project_id = "yzzgkjwyhnvlyqldvzxf"

[functions.send-telegram]
verify_jwt = false

[functions.invite-client]
verify_jwt = false

[functions.telegram-webhook]
verify_jwt = false

[functions.delete-client]
verify_jwt = false

[functions.deduct-sessions]
verify_jwt = false

[functions.whoop-auth]
verify_jwt = false

[functions.whoop-sync]
verify_jwt = false

[functions.whoop-cron]
verify_jwt = false
