// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-clients.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/tools/_shared.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
async function isTrainer(ctx) {
  const supabase = supabaseForUser(ctx);
  const { data, error } = await supabase.from("user_roles").select("role").eq("user_id", ctx.getUserId()).eq("role", "trainer").maybeSingle();
  if (error) {
    console.error("isTrainer error:", error);
    return false;
  }
  return !!data;
}
function requireAuth(ctx) {
  if (!ctx.isAuthenticated()) {
    return false;
  }
  return true;
}
function notAuthenticatedResponse() {
  return {
    content: [
      { type: "text", text: "Not authenticated. Please complete OAuth sign-in." }
    ],
    isError: true
  };
}
function forbiddenResponse() {
  return {
    content: [
      { type: "text", text: "You do not have permission to access this data." }
    ],
    isError: true
  };
}

// src/lib/mcp/tools/list-clients.ts
var list_clients_default = defineTool({
  name: "list_clients",
  title: "List clients",
  description: "List clients accessible to the signed-in user. Trainers see all clients they work with; clients see their own profile.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).optional().describe("Maximum number of clients to return (1-100)."),
    search: z.string().max(100).optional().describe("Optional name or email substring to filter clients.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit = 50, search }, ctx) => {
    if (!requireAuth(ctx)) return notAuthenticatedResponse();
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const trainer = await isTrainer(ctx);
    let clientUserIds = [];
    if (trainer) {
      const tables = [
        { table: "scheduled_sessions", column: "user_id" },
        { table: "body_measurements", column: "user_id" }
      ];
      for (const { table, column } of tables) {
        const { data: data2, error: error2 } = await supabase.from(table).select(column).eq("trainer_user_id", userId);
        if (error2) {
          console.error(`list_clients: error reading ${table}:`, error2);
          continue;
        }
        for (const row of data2 || []) {
          const value = row[column];
          if (typeof value === "string" && !clientUserIds.includes(value)) {
            clientUserIds.push(value);
          }
        }
      }
    } else {
      clientUserIds = [userId];
    }
    if (clientUserIds.length === 0) {
      return {
        content: [{ type: "text", text: JSON.stringify({ clients: [] }) }],
        structuredContent: { clients: [] }
      };
    }
    let query = supabase.from("profiles").select("id, user_id, full_name, email, phone, avatar_url, archived_at, nutrition_goal, daily_calorie_goal").in("user_id", clientUserIds).order("full_name", { ascending: true });
    if (search?.trim()) {
      const term = search.trim().toLowerCase();
      query = query.or(`full_name.ilike.%${term}%,email.ilike.%${term}%`);
    }
    const { data, error } = await query.limit(limit);
    if (error) {
      return {
        content: [{ type: "text", text: `Error listing clients: ${error.message}` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify({ clients: data ?? [] }) }],
      structuredContent: { clients: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-sessions.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^4.4.3";
var list_sessions_default = defineTool2({
  name: "list_sessions",
  title: "List scheduled sessions",
  description: "List scheduled training sessions for a client. Trainers may query any of their clients; clients may only query themselves.",
  inputSchema: {
    client_user_id: z2.string().uuid().optional().describe("User ID of the client. Omit to query the signed-in user's own sessions."),
    from_date: z2.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Start date in YYYY-MM-DD format."),
    to_date: z2.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("End date in YYYY-MM-DD format."),
    limit: z2.number().int().min(1).max(200).optional().describe("Maximum sessions to return (1-200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ client_user_id, from_date, to_date, limit = 50 }, ctx) => {
    if (!requireAuth(ctx)) return notAuthenticatedResponse();
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const trainer = await isTrainer(ctx);
    const targetUserId = client_user_id ?? userId;
    if (!trainer && targetUserId !== userId) {
      return forbiddenResponse();
    }
    if (trainer) {
      const { data: checkData, error: checkError } = await supabase.from("scheduled_sessions").select("id").eq("trainer_user_id", userId).eq("user_id", targetUserId).limit(1);
      if (checkError || !checkData || checkData.length === 0) {
        return forbiddenResponse();
      }
    }
    let query = supabase.from("scheduled_sessions").select("*").eq("user_id", targetUserId).order("session_date", { ascending: true }).order("session_time", { ascending: true });
    if (from_date) query = query.gte("session_date", from_date);
    if (to_date) query = query.lte("session_date", to_date);
    const { data, error } = await query.limit(limit);
    if (error) {
      return {
        content: [{ type: "text", text: `Error listing sessions: ${error.message}` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify({ sessions: data ?? [] }) }],
      structuredContent: { sessions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-client-summary.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^4.4.3";
var get_client_summary_default = defineTool3({
  name: "get_client_summary",
  title: "Get client summary",
  description: "Return a summary of a client: profile, active packages, recent sessions, body measurements, nutrition streak/achievements, and latest test result. Trainers may query their clients; clients may only query themselves.",
  inputSchema: {
    client_user_id: z3.string().uuid().describe("User ID of the client to summarize.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ client_user_id }, ctx) => {
    if (!requireAuth(ctx)) return notAuthenticatedResponse();
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const trainer = await isTrainer(ctx);
    if (!trainer && client_user_id !== userId) {
      return forbiddenResponse();
    }
    if (trainer) {
      const { data: checkData, error: checkError } = await supabase.from("scheduled_sessions").select("id").eq("trainer_user_id", userId).eq("user_id", client_user_id).limit(1);
      if (checkError || !checkData || checkData.length === 0) {
        return forbiddenResponse();
      }
    }
    const [
      profileRes,
      packagesRes,
      sessionsRes,
      measurementsRes,
      nutritionRes,
      achievementsRes,
      testsRes
    ] = await Promise.all([
      supabase.from("profiles").select("*").eq("user_id", client_user_id).maybeSingle(),
      supabase.from("client_packages").select("*").eq("user_id", client_user_id).order("created_at", { ascending: false }).limit(10),
      supabase.from("scheduled_sessions").select("id, session_date, session_time, duration_minutes, is_deducted, notes").eq("user_id", client_user_id).order("session_date", { ascending: false }).limit(10),
      supabase.from("body_measurements").select("*").eq("user_id", client_user_id).order("measured_at", { ascending: false }).limit(5),
      supabase.from("nutrition_logs").select("log_date, ai_score, ai_feedback, water_ml, alcohol_ml, coffee_cups, tea_cups, notes").eq("user_id", client_user_id).order("log_date", { ascending: false }).limit(7),
      supabase.from("client_achievements").select("achievement_key, title_en, title_ru, earned_at").eq("user_id", client_user_id).order("earned_at", { ascending: false }).limit(10),
      supabase.from("test_results").select("*").eq("user_id", client_user_id).order("created_at", { ascending: false }).limit(1)
    ]);
    const summary = {
      profile: profileRes.data ?? null,
      packages: packagesRes.data ?? [],
      recent_sessions: sessionsRes.data ?? [],
      recent_measurements: measurementsRes.data ?? [],
      recent_nutrition: nutritionRes.data ?? [],
      recent_achievements: achievementsRes.data ?? [],
      latest_test: testsRes.data?.[0] ?? null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/tools/list-nutrition-logs.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^4.4.3";
var list_nutrition_logs_default = defineTool4({
  name: "list_nutrition_logs",
  title: "List nutrition logs",
  description: "List nutrition diary entries for a client. Trainers may query their clients; clients may only query themselves.",
  inputSchema: {
    client_user_id: z4.string().uuid().optional().describe("User ID of the client. Omit to query the signed-in user's own logs."),
    from_date: z4.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Start date in YYYY-MM-DD format."),
    to_date: z4.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("End date in YYYY-MM-DD format."),
    limit: z4.number().int().min(1).max(200).optional().describe("Maximum logs to return (1-200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ client_user_id, from_date, to_date, limit = 30 }, ctx) => {
    if (!requireAuth(ctx)) return notAuthenticatedResponse();
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const trainer = await isTrainer(ctx);
    const targetUserId = client_user_id ?? userId;
    if (!trainer && targetUserId !== userId) {
      return forbiddenResponse();
    }
    if (trainer) {
      const { data: checkData, error: checkError } = await supabase.from("scheduled_sessions").select("id").eq("trainer_user_id", userId).eq("user_id", targetUserId).limit(1);
      if (checkError || !checkData || checkData.length === 0) {
        return forbiddenResponse();
      }
    }
    let query = supabase.from("nutrition_logs").select("*").eq("user_id", targetUserId).order("log_date", { ascending: false });
    if (from_date) query = query.gte("log_date", from_date);
    if (to_date) query = query.lte("log_date", to_date);
    const { data, error } = await query.limit(limit);
    if (error) {
      return {
        content: [{ type: "text", text: `Error listing nutrition logs: ${error.message}` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify({ nutrition_logs: data ?? [] }) }],
      structuredContent: { nutrition_logs: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-body-measurements.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z5 } from "npm:zod@^4.4.3";
var list_body_measurements_default = defineTool5({
  name: "list_body_measurements",
  title: "List body measurements",
  description: "List body measurements for a client. Trainers may query their clients; clients may only query themselves.",
  inputSchema: {
    client_user_id: z5.string().uuid().optional().describe("User ID of the client. Omit to query the signed-in user's own measurements."),
    limit: z5.number().int().min(1).max(100).optional().describe("Maximum measurements to return (1-100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ client_user_id, limit = 20 }, ctx) => {
    if (!requireAuth(ctx)) return notAuthenticatedResponse();
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const trainer = await isTrainer(ctx);
    const targetUserId = client_user_id ?? userId;
    if (!trainer && targetUserId !== userId) {
      return forbiddenResponse();
    }
    if (trainer) {
      const { data: checkData, error: checkError } = await supabase.from("body_measurements").select("id").eq("trainer_user_id", userId).eq("user_id", targetUserId).limit(1);
      if (checkError || !checkData || checkData.length === 0) {
        return forbiddenResponse();
      }
    }
    const { data, error } = await supabase.from("body_measurements").select("*").eq("user_id", targetUserId).order("measured_at", { ascending: false }).limit(limit);
    if (error) {
      return {
        content: [{ type: "text", text: `Error listing body measurements: ${error.message}` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify({ body_measurements: data ?? [] }) }],
      structuredContent: { body_measurements: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "yzzgkjwyhnvlyqldvzxf";
var mcp_default = defineMcp({
  name: "limassol-fitness-mcp",
  title: "Limassol Fitness",
  version: "0.1.0",
  instructions: "Read-only access to the Limassol Fitness trainer dashboard. Trainers can list their clients, view scheduled sessions, and read client summaries including packages, nutrition, body measurements, and achievements. Clients can read only their own data. All access is scoped by Supabase RLS and user roles.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_clients_default,
    list_sessions_default,
    get_client_summary_default,
    list_nutrition_logs_default,
    list_body_measurements_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
